### PR TITLE
2.3

### PR DESCRIPTION
**Pull request by jwmak**
Release CUDPP v2.3, with multisplit added.

### CODE REVIEW

**Comment by jowens** [comment]
@jwmak I am derelict for not looking at this yet, but thank you for bringing it home. @sashkiani can you take a peek as well please?

**Comment by sashkiani** [comment]
@jwmak @jowens Thanks, I'll take a look this weekend. I'm a bit overloaded right now.

**Comment by harrism** [comment]
It says "multisplit added, but not working". Can you get it working before doing a pull request?

**Comment by jowens** [comment]
@jwmak Any response to Mark's question? Since multisplit is the new thing in this release, I agree.

**Comment by jwmak** [comment]
Sorry, the "not working" message was from the very first commit of this branch. The latest commit now states that multisplit is working.

**Pull request merged**
